CLI: reserve, unreserve (手動予約/解除) コマンド 実装

diff --git a/chinachu b/chinachu
--- a/chinachu
+++ b/chinachu
@@ -55,6 +55,7 @@ main () {
   shift
   case $cmd in
     installer | service | update | search | \
+    reserve | unreserve | \
     rule | enrule | disrule | rmrule | \
     rules | reserves | recording | recorded | \
     cleanup | unlock | ircbot )
@@ -341,6 +342,35 @@ chinachu_update () {
 
 chinachu_search () {
   ${NAVE_DIR}/node app-cli.js -mode search "$@" && return 0
+}
+
+chinachu_reserve () {
+  if [ ! "$1" ]; then
+    fail "Usage: reserve <pgid>"
+  fi
+  
+  ${NAVE_DIR}/node app-cli.js -mode reserve -id "$1" || fail "couldn't reserve $1"
+  
+  while [ 1 ]; do
+    echo -n "Run a scheduler [Y/n]? "
+    read line
+    case $line in
+      [yY])
+        ${NAVE_DIR}/node app-scheduler.js > /dev/stdout 2>&1 | tee ./log/scheduler && return 0
+        ;;
+      [nN])
+        echo "Ok." && return 0
+        ;;
+    esac
+  done
+}
+
+chinachu_unreserve () {
+  if [ ! "$1" ]; then
+    fail "Usage: unreserve <pgid>"
+  fi
+  
+  ${NAVE_DIR}/node app-cli.js -mode unreserve -id "$1" || fail "couldn't unreserve $1"
 }
 
 chinachu_rule () {
